# Generated by Django 3.1.5 on 2021-02-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedplace',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='infectedplace',
            name='lng',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
