# Generated by Django 3.1.5 on 2021-02-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20210201_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedplace',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
