# Generated by Django 3.1.5 on 2021-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_infectedplace_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedplace',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='infectedplace',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
