# Generated by Django 3.1.5 on 2021-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20210202_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedplace',
            name='happened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
