# Generated by Django 3.1.5 on 2021-02-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_infectedplace_happened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedplace',
            name='reported2oie_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
