# Generated by Django 3.1.5 on 2021-02-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_infectedplace_reported2oie_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedplace',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
