# Generated by Django 3.1.5 on 2021-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20210203_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedplace',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
