# Generated by Django 3.1.5 on 2021-02-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_infectedplace_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='infectedplace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
